######################################################################
# Automatically generated by qmake (3.1) Sun May 28 16:01:07 2023
######################################################################

TEMPLATE = app
TARGET = neophyte
INCLUDEPATH += .
QT += widgets
QT += webenginewidgets
# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += mainwindow.h custombutton.h timelogic.h heatmap.h heatmaptotal.h
SOURCES += main.cpp mainwindow.cpp custombutton.cpp timelogic.cpp heatmap.cpp heatmaptotal.cpp
FORMS += mainwindow.ui sliders.ui
RESSOURCES += ressources.qrc
