######################################################################
# Automatically generated by qmake (3.1) Fri Jul 14 10:32:58 2023
######################################################################

TEMPLATE = app
TARGET = neophyte
INCLUDEPATH += .
QT += widgets
QT += webenginewidgets
# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += custombutton.h \
           heatmap.h \
           heatmaptotal.h \
           mainwindow.h \
           timelogic.h \
           ui_mainwindow.h \
           ui_menu.h \
           ui_sliders.h \
           skills.h 
FORMS += mainwindow.ui 
SOURCES += custombutton.cpp \
           heatmap.cpp \
           heatmaptotal.cpp \
           main.cpp \
           mainwindow.cpp \
           timelogic.cpp 
RESOURCES += ressources.qrc
